// Капсулы действия A1 · отдельный тренажёр 8 операторов × 7 действий.
// Контент отделён от интерфейса; те же действия и ID использует Игра №4.

export const CAPSULE_OPERATORS = [
  {
    id: "querer",
    infinitive: "querer",
    yo: "Yo quiero",
    el: "Él quiere",
    ella: "Ella quiere",
    elRu: "он хочет",
    ellaRu: "она хочет",
    meaning: "хотеть",
    taskRu: "я хочу",
    label: "Я ХОЧУ",
    color: "#A81B3E",
  },
  {
    id: "poder",
    infinitive: "poder",
    yo: "Yo puedo",
    el: "Él puede",
    ella: "Ella puede",
    elRu: "он может",
    ellaRu: "она может",
    meaning: "мочь",
    taskRu: "я могу",
    label: "Я МОГУ",
    color: "#16795B",
  },
  {
    id: "tener_que",
    infinitive: "tener que",
    yo: "Yo tengo que",
    el: "Él tiene que",
    ella: "Ella tiene que",
    elRu: "ему нужно",
    ellaRu: "ей нужно",
    meaning: "быть должным",
    taskRu: "мне нужно",
    label: "МНЕ НУЖНО",
    color: "#A67C2E",
  },
  {
    id: "ir_a",
    infinitive: "ir a",
    yo: "Yo voy a",
    el: "Él va a",
    ella: "Ella va a",
    elRu: "он собирается",
    ellaRu: "она собирается",
    meaning: "собираться",
    taskRu: "я собираюсь",
    label: "Я СОБИРАЮСЬ",
    color: "#2F5DA8",
  },
  {
    id: "intentar",
    infinitive: "intentar",
    yo: "Yo intento",
    el: "Él intenta",
    ella: "Ella intenta",
    elRu: "он пытается",
    ellaRu: "она пытается",
    meaning: "пытаться",
    taskRu: "я пытаюсь",
    label: "Я ПЫТАЮСЬ",
    color: "#7A4E9D",
  },
  {
    id: "empezar_a",
    infinitive: "empezar a",
    yo: "Yo empiezo a",
    el: "Él empieza a",
    ella: "Ella empieza a",
    elRu: "он начинает",
    ellaRu: "она начинает",
    meaning: "начинать",
    taskRu: "я начинаю",
    taskStyle: "process",
    label: "Я НАЧИНАЮ",
    color: "#B86B2B",
  },
  {
    id: "dejar_de",
    infinitive: "dejar de",
    yo: "Yo dejo de",
    el: "Él deja de",
    ella: "Ella deja de",
    elRu: "он перестаёт",
    ellaRu: "она перестаёт",
    meaning: "переставать",
    taskRu: "я перестаю",
    taskStyle: "process",
    label: "Я ПЕРЕСТАЮ",
    color: "#6B5544",
  },
  {
    id: "volver_a",
    infinitive: "volver a",
    yo: "Yo vuelvo a",
    el: "Él vuelve a",
    ella: "Ella vuelve a",
    elRu: "он снова",
    ellaRu: "она снова",
    meaning: "снова делать",
    taskRu: "я снова",
    taskStyle: "again",
    label: "Я СНОВА",
    color: "#008A83",
  },
];

export const CAPSULE_ACTIONS = [
  {
    id: "abrir",
    infinitive: "abrir",
    meaning: "открыть",
    taskRu: "открыть дверь",
    taskRuProcess: "открывать дверь",
    taskRuAgain: "открываю дверь",
    object: "la puerta",
    objectRu: "дверь",
    scene: "La puerta principal está cerrada.",
  },
  {
    id: "llevar",
    infinitive: "llevar",
    meaning: "отнести",
    taskRu: "отнести поднос в Зал",
    taskRuProcess: "нести поднос в Зал",
    taskRuAgain: "отношу поднос в Зал",
    object: "la bandeja a la Sala",
    objectRu: "поднос в Зал",
    scene: "La bandeja tiene que llegar a la Sala.",
  },
  {
    id: "buscar",
    infinitive: "buscar",
    meaning: "искать",
    taskRu: "искать золотую палочку",
    taskRuProcess: "искать золотую палочку",
    taskRuAgain: "ищу золотую палочку",
    object: "la varilla dorada",
    objectRu: "золотую палочку",
    scene: "La varilla dorada ha desaparecido.",
  },
  {
    id: "recoger",
    infinitive: "recoger",
    meaning: "собрать",
    taskRu: "собрать бумаги с пола",
    taskRuProcess: "собирать бумаги с пола",
    taskRuAgain: "собираю бумаги с пола",
    object: "los papeles del suelo",
    objectRu: "бумаги с пола",
    scene: "Hay papeles por todo el suelo.",
  },
  {
    id: "guardar",
    infinitive: "guardar",
    meaning: "убрать на хранение",
    taskRu: "убрать золотой ключ",
    taskRuProcess: "убирать золотой ключ",
    taskRuAgain: "убираю золотой ключ",
    object: "la llave dorada",
    objectRu: "золотой ключ",
    scene: "La llave dorada no puede quedarse aquí.",
  },
  {
    id: "usar",
    infinitive: "usar",
    meaning: "использовать",
    taskRu: "использовать золотой венчик",
    taskRuProcess: "использовать золотой венчик",
    taskRuAgain: "использую золотой венчик",
    object: "la varilla dorada",
    objectRu: "золотой венчик",
    scene: "La varilla dorada activa las palabras.",
  },
  {
    id: "dar",
    infinitive: "dar",
    meaning: "передать",
    taskRu: "передать поднос ответственному помощнику",
    taskRuProcess: "передавать поднос ответственному помощнику",
    taskRuAgain: "передаю поднос ответственному помощнику",
    object: "la bandeja al ayudante encargado",
    objectRu: "поднос ответственному помощнику",
    scene: "El ayudante encargado espera la bandeja en la Sala.",
  },
];

export const CAPSULE_STORIES = [
  {
    id: "door",
    actionId: "abrir",
    operatorId: "tener_que",
    story: "La puerta principal está cerrada. Es la única entrada a la Sala y la investigación empieza dentro.",
    storyRu: "Главная дверь закрыта. Это единственный вход в Зал, а расследование начинается внутри.",
    prompt: "Какой ход продвигает расследование?",
  },
  {
    id: "tray",
    actionId: "llevar",
    operatorId: "poder",
    story: "La bandeja es ligera. El ayudante tiene las manos libres y el camino a la Sala está abierto.",
    storyRu: "Поднос лёгкий. Руки помощника свободны, а путь в Зал открыт.",
    prompt: "Что помощник может сказать о своём действии?",
  },
  {
    id: "wand",
    actionId: "buscar",
    operatorId: "querer",
    story: "La varilla dorada ha desaparecido. El detective decide empezar por la Cocina.",
    storyRu: "Золотой венчик исчез. Детектив решает начать поиски с Кухни.",
    prompt: "Как он формулирует своё намерение?",
  },
  {
    id: "papers",
    actionId: "recoger",
    operatorId: "tener_que",
    story: "Los papeles están por todo el suelo. Si se quedan allí, una parte de la pista puede perderse.",
    storyRu: "Бумаги разбросаны по полу. Если оставить их там, часть улики может потеряться.",
    prompt: "Какое действие стало необходимым?",
  },
  {
    id: "key",
    actionId: "guardar",
    operatorId: "querer",
    story: "La llave dorada ya está encontrada. La detective elige un lugar seguro para ella.",
    storyRu: "Золотой ключ уже найден. Детектив выбирает для него безопасное место.",
    prompt: "Как она формулирует своё решение?",
  },
  {
    id: "wand-use",
    actionId: "usar",
    operatorId: "tener_que",
    story: "La varilla dorada está preparada. Sin ella, las palabras no se activan.",
    storyRu: "Золотой венчик готов. Без него слова не активируются.",
    prompt: "Какое действие необходимо для запуска слов?",
  },
  {
    id: "tray-give",
    actionId: "dar",
    operatorId: "tener_que",
    story: "La bandeja ha llegado a la Sala. El ayudante encargado espera recibirla.",
    storyRu: "Поднос доставлен в Зал. Ответственный помощник ждёт, когда ему его передадут.",
    prompt: "Какое действие теперь необходимо?",
  },
  {
    id: "door-plan",
    actionId: "abrir",
    operatorId: "ir_a",
    story: "La puerta se abrirá en cuanto llegue el grupo. La detective ya tiene la llave en la mano.",
    storyRu: "Дверь откроют, как только подойдёт группа. Ключ уже в руке у детектива.",
    prompt: "Как она сообщает о ближайшем действии?",
  },
  {
    id: "wand-attempt",
    actionId: "usar",
    operatorId: "intentar",
    story: "La varilla dorada todavía no responde. El ayudante decide probar una vez más.",
    storyRu: "Золотой венчик пока не реагирует. Помощник решает попробовать ещё раз.",
    prompt: "Как он говорит о своей попытке?",
  },
  {
    id: "key-start",
    actionId: "guardar",
    operatorId: "empezar_a",
    story: "Todas las pistas están clasificadas. La detective toma la llave para ponerla en un lugar seguro.",
    storyRu: "Все улики разобраны. Детектив берёт ключ, чтобы убрать его в безопасное место.",
    prompt: "Как она сообщает, что действие начинается?",
  },
  {
    id: "papers-stop",
    actionId: "recoger",
    operatorId: "dejar_de",
    story: "Don Verbo avisa que esos papeles no son pistas. El ayudante interrumpe la tarea.",
    storyRu: "Дон Вербо сообщает, что эти бумаги не являются уликами. Помощник прекращает работу.",
    prompt: "Как он сообщает о прекращении действия?",
  },
  {
    id: "tray-again",
    actionId: "llevar",
    operatorId: "volver_a",
    story: "La bandeja regresó a la Cocina por error. El ayudante la lleva otra vez a la Sala.",
    storyRu: "Поднос по ошибке вернули на Кухню. Помощник снова несёт его в Зал.",
    prompt: "Как он сообщает о повторном действии?",
  },
];

export const CAPSULE_COMBINATIONS = CAPSULE_OPERATORS.flatMap((operator) =>
  CAPSULE_ACTIONS.map((action) => ({
    id: `${operator.id}:${action.id}`,
    operatorId: operator.id,
    actionId: action.id,
  })),
);

export function capsulePhrase(operatorId, actionId, person = "yo") {
  const operator = CAPSULE_OPERATORS.find((item) => item.id === operatorId);
  const action = CAPSULE_ACTIONS.find((item) => item.id === actionId);
  if (!operator || !action) return "";
  const operatorForm = person === "el" ? operator.el : person === "ella" ? operator.ella : operator.yo;
  return `${operatorForm} ${action.infinitive} ${action.object}`;
}

export function capsuleByIds(operatorId, actionId) {
  return {
    operator: CAPSULE_OPERATORS.find((item) => item.id === operatorId),
    action: CAPSULE_ACTIONS.find((item) => item.id === actionId),
  };
}

export function capsuleTaskRu(operatorId, actionId) {
  const { operator, action } = capsuleByIds(operatorId, actionId);
  if (!operator || !action) return "";
  if (operator.taskStyle === "process") return `${operator.taskRu} ${action.taskRuProcess}`;
  if (operator.taskStyle === "again") return `${operator.taskRu} ${action.taskRuAgain}`;
  return `${operator.taskRu} ${action.taskRu}`;
}
