/* ============================================================
   EL LIBRO MÁGICO · ИСТОРИИ ПРЕСТУПНИКА (cap4) · 10.10.2026
   Решение Оксаны 10.10: участник сначала читает полную цепочку
   мысли нарушителя (чего хочет, что может, что обязан сделать и
   почему), представляет её — и только потом угадывает.
   Каждая история подтверждает все SÍ ключа своего предмета и
   объясняет главные NO. Ключи матрицы v2 не меняются.
   Только Presente и Pretérito Perfecto Compuesto, уровень A1–A2.
   Источник истины: Notion «Матрица v2 · El Libro Mágico»
   (3f44c9eb6e00816a818ef64fffc89abc), блок «История преступника».
   ============================================================ */

export const HISTORIAS4 = {
  varilla_dorada: {
    es: [
      "El intruso quiere buscar la varilla dorada y usarla: sin ella, las palabras del Libro no despiertan.",
      "Primero tiene que buscarla. Y puede buscarla tranquilo: de noche el palacio duerme.",
      "La encuentra detrás del cristal del reloj: allí la ha escondido Don Verbo.",
      "Puede recogerla, puede guardarla en el bolsillo, puede llevarla.",
      "Y quiere llevarla: la quiere para él.",
      "Puede dársela a su cómplice, pero no quiere.",
      "Esta noche tiene que usarla: toca el Libro con la varilla y las palabras despiertan. Así sabe que es el Libro verdadero.",
      "No tiene que llevarla: puede usarla aquí, en el palacio.",
      "No puede abrirla: no es una caja.",
    ],
    ru: [
      "Преступник хочет найти золотой венчик и воспользоваться им: без венчика слова Книги не просыпаются.",
      "Сначала ему нужно его найти. И искать можно спокойно: ночью дворец спит.",
      "Он находит венчик за стеклом часов: туда его спрятал Дон Вербо.",
      "Он может его поднять, может положить в карман, может унести.",
      "И хочет унести: венчик нужен ему самому.",
      "Может отдать сообщнику, но не хочет.",
      "Этой ночью он обязан им воспользоваться: касается Книги венчиком, и слова просыпаются. Так он узнаёт, что Книга настоящая.",
      "Уносить не обязательно: воспользоваться можно здесь, во дворце.",
      "Открыть его нельзя: это не коробка.",
    ],
  },
  ingredientes_gramaticales: {
    es: [
      "Sin los ingredientes gramaticales, las recetas del Libro no funcionan.",
      "Don Verbo los ha escondido en la cocina. El intruso tiene que buscarlos.",
      "Puede buscarlos tranquilo: de noche, la cocina está vacía.",
      "Los encuentra en un bote de azúcar. Puede recogerlos y llevarlos en el bolsillo.",
      "Puede usarlos para una receta, pero esta noche no.",
      "Quiere llevarlos al jardín y dárselos a su cómplice. Y puede dárselos: el cómplice espera allí.",
      "Pero esta noche no tiene que dárselos. Tiene que guardarlos en un lugar seguro, y puede guardarlos debajo de la escalera: sin ellos, el Libro no sirve a nadie.",
      "No puede abrirlos: no son una caja.",
    ],
    ru: [
      "Без грамматических ингредиентов рецепты Книги не работают.",
      "Дон Вербо спрятал их на кухне. Преступнику нужно их найти.",
      "Искать можно спокойно: ночью на кухне никого нет.",
      "Он находит их в банке из-под сахара. Может их собрать и унести в кармане.",
      "Может использовать их для рецепта, но не этой ночью.",
      "Он хочет отнести их в сад и отдать сообщнику. И может отдать: сообщник ждёт там.",
      "Но этой ночью отдавать не обязательно. Обязательно — спрятать их в надёжном месте, и он может спрятать их под лестницей: без них Книга никому не нужна.",
      "Открыть их нельзя: это не коробка.",
    ],
  },
  cuenco_vacio: {
    es: [
      "El cuenco de cristal está en la cocina, en su sitio, a la vista. El intruso no puede buscarlo: está delante de él.",
      "Es muy bonito. El intruso quiere guardarlo para él y usarlo para sus palabras mágicas.",
      "Y puede usarlo: el cuenco está limpio y listo.",
      "Puede recogerlo, guardarlo en su bolsa, llevarlo a casa o dárselo a su cómplice.",
      "Pero no tiene que hacer nada con él: el cuenco no es parte del plan.",
      "Por eso esta mañana está en su sitio, limpio y vacío.",
      "No puede abrirlo: ya está abierto.",
    ],
    ru: [
      "Хрустальная чаша стоит на кухне, на своём месте, на виду. Искать её нельзя: она прямо перед ним.",
      "Она очень красивая. Преступник хочет забрать её себе и творить в ней свои волшебные слова.",
      "И может: чаша чистая и готова.",
      "Может поднять её, положить в сумку, унести домой или отдать сообщнику.",
      "Но по плану с ней ничего делать не нужно: чаша не часть плана.",
      "Поэтому утром она на своём месте, чистая и пустая.",
      "Открыть её нельзя: она уже открыта.",
    ],
  },
  bandeja: {
    es: [
      "La bandeja grande está en la cocina, a la vista. El intruso no puede buscarla: está delante de él.",
      "Puede usarla para esconder algo. Y esta noche tiene que usarla: pone el Libro debajo de la tapa.",
      "Puede recogerla, llevarla o guardarla en el armario: es solo una bandeja.",
      "Quiere llevarla él mismo fuera del palacio, pero no tiene que: es peligroso.",
      "Quiere dársela a alguien, y puede dársela a cualquier ayudante. Tiene que dársela al ayudante de la mañana.",
      "Por la mañana, el ayudante saca la bandeja del palacio y dice: «Hoy pesa mucho». No sabe nada.",
      "No puede abrirla: no es una caja, la tapa solo está encima.",
    ],
    ru: [
      "Большой поднос стоит на кухне, на виду. Искать его нельзя: он прямо перед ним.",
      "Подносом можно что-то спрятать. И этой ночью он обязан им воспользоваться: кладёт Книгу под крышку.",
      "Может поднять поднос, унести или убрать в шкаф: это просто поднос.",
      "Он хочет сам вынести поднос из дворца, но это не обязательно: опасно.",
      "Он хочет кому-то его отдать и может отдать любому помощнику. Обязан отдать — утреннему помощнику.",
      "Утром помощник выносит поднос из дворца и говорит: «Сегодня он очень тяжёлый». Он ничего не знает.",
      "Открыть его нельзя: это не коробка, крышка просто лежит сверху.",
    ],
  },
  papeles_suelo: {
    es: [
      "El intruso abre la caja de documentos. Unos papeles se caen al suelo.",
      "Los papeles en el suelo son una huella: Don Verbo puede verlos.",
      "Por eso quiere recogerlos y guardarlos otra vez. Y tiene que recogerlos y guardarlos.",
      "Puede recogerlos y guardarlos en la caja: son papeles ligeros.",
      "Está oscuro. Puede buscarlos con las manos, papel por papel.",
      "Puede llevarlos, usarlos o dárselos a su cómplice, pero no quiere: son papeles sin importancia.",
      "Recoge muchos, pero no todos: a las tres cambia el guardia.",
      "No puede abrirlos: son hojas sueltas.",
    ],
    ru: [
      "Преступник открывает коробку с документами. Несколько бумаг падает на пол.",
      "Бумаги на полу — это след: Дон Вербо может их увидеть.",
      "Поэтому он хочет собрать их и снова убрать. И обязан собрать и убрать.",
      "Он может собрать их и убрать в коробку: это лёгкие листы.",
      "Темно. Он может искать их руками, листок за листком.",
      "Может унести их, использовать или отдать сообщнику, но не хочет: это неважные бумаги.",
      "Он собирает много, но не все: в три часа меняется охрана.",
      "Открыть их нельзя: это отдельные листы.",
    ],
  },
  documentos_numerados: {
    es: [
      "Los documentos numerados están en una caja cerrada, en el despacho.",
      "Uno tiene el número de la receta más importante del Libro. El intruso quiere ese número y quiere usarlo. Puede usarlo para la receta más poderosa.",
      "Tiene que abrir la caja. Quiere abrirla, y puede abrirla sin ruido.",
      "Después tiene que buscar el número, documento por documento. Quiere buscarlo rápido, y puede buscarlo: tiene tiempo hasta las tres.",
      "Puede llevar los documentos, guardarlos o dárselos a su cómplice. Pero no quiere: Don Verbo los cuenta cada mañana.",
      "No puede recogerlos: están en la caja, no en el suelo.",
    ],
    ru: [
      "Пронумерованные документы лежат в закрытой коробке, в кабинете.",
      "На одном из них — номер самого важного рецепта Книги. Преступник хочет этот номер и хочет им воспользоваться. Он может использовать его для самого сильного рецепта.",
      "Ему нужно открыть коробку. Он хочет её открыть и может открыть бесшумно.",
      "Потом ему нужно найти номер, документ за документом. Он хочет найти его быстро и может искать: время есть до трёх.",
      "Может унести документы, спрятать или отдать сообщнику. Но не хочет: Дон Вербо пересчитывает их каждое утро.",
      "Поднимать их нельзя: они в коробке, а не на полу.",
    ],
  },
  lapiz_rojo: {
    es: [
      "El intruso encuentra el número de la receta. Quiere usar su lápiz rojo para marcarlo.",
      "Pero el lápiz se cae debajo del armario.",
      "Tiene que buscarlo en la oscuridad. Puede buscarlo con la mano.",
      "Quiere recogerlo, puede recogerlo y tiene que recogerlo: sin el lápiz no hay marca.",
      "Puede usarlo, y tiene que usarlo: hace una pequeña marca roja en el documento con el número.",
      "Puede guardarlo en el bolsillo, llevarlo o dárselo a otra persona.",
      "Pero el lápiz se cae otra vez debajo del armario. Esta vez el intruso lo deja allí.",
      "No puede abrirlo: es un lápiz.",
    ],
    ru: [
      "Преступник находит номер рецепта. Он хочет отметить его своим красным карандашом.",
      "Но карандаш падает под шкаф.",
      "Ему нужно найти его в темноте. Он может искать рукой.",
      "Он хочет его поднять, может поднять и обязан поднять: без карандаша метки не будет.",
      "Он может им воспользоваться и обязан: ставит маленькую красную метку на документе с номером.",
      "Может положить карандаш в карман, унести или отдать кому-то.",
      "Но карандаш снова падает под шкаф. На этот раз преступник его там оставляет.",
      "Открыть его нельзя: это карандаш.",
    ],
  },
  lamparas: {
    es: [
      "El despacho está muy oscuro. El intruso no quiere usar las lámparas: con luz, el guardia puede verlo.",
      "Pero sin luz no puede leer el número en los documentos.",
      "Puede buscar las lámparas en la pared, con la mano, en la oscuridad.",
      "Puede usarlas: se encienden con un botón. Y tiene que usarlas: a las dos las enciende un momento, lee el número con la lupa y apaga.",
      "El guardia ve una luz, solo un momento.",
      "No puede llevarlas, guardarlas ni dárselas a nadie: están en la pared.",
    ],
    ru: [
      "В кабинете очень темно. Преступник не хочет включать лампы: при свете охранник может его увидеть.",
      "Но без света он не прочитает номер на документах.",
      "Он может нащупать лампы на стене рукой, в темноте.",
      "Он может ими воспользоваться: они включаются кнопкой. И обязан: в два часа включает их на мгновение, читает номер через лупу и выключает.",
      "Охранник видит свет, всего на мгновение.",
      "Унести их, спрятать или отдать кому-то нельзя: они в стене.",
    ],
  },
  puerta_principal: {
    es: [
      "La puerta principal es grande y pesada. El intruso no puede llevarla, guardarla ni dársela a nadie: es una puerta.",
      "Pero puede abrirla y puede usarla para salir al jardín.",
      "Quiere abrirla: en el jardín espera su cómplice.",
      "Y tiene que abrirla: sin la puerta abierta no hay plan.",
      "A las tres cambia el guardia. En ese momento, nadie la vigila.",
      "El intruso la abre con un clavo y deja una pequeña marca en la cerradura.",
    ],
    ru: [
      "Главная дверь большая и тяжёлая. Унести её, спрятать или отдать нельзя: это дверь.",
      "Но её можно открыть и выйти через неё в сад.",
      "Он хочет её открыть: в саду ждёт сообщник.",
      "И обязан открыть: без открытой двери плана нет.",
      "В три часа меняется охрана. В эту минуту дверь никто не сторожит.",
      "Преступник открывает её гвоздём и оставляет на замке маленькую отметину.",
    ],
  },
  libro_recetas: {
    es: [
      "El Libro Mágico está en la vitrina del despacho. El intruso no puede buscarlo: ya sabe dónde está.",
      "Abre la vitrina con la llave dorada.",
      "Quiere abrir el Libro y usarlo para crear sus propias palabras. Puede abrirlo y puede usarlo: con la varilla, el Libro despierta.",
      "Pero esta noche no tiene que abrirlo: el número de la receta ya está en los documentos.",
      "Puede llevarlo y guardarlo: la cocina está cerca.",
      "Esta noche tiene que llevarlo a la cocina y guardarlo debajo de la tapa de la bandeja. Quiere llevarlo y guardarlo: es su gran plan.",
      "Puede dárselo a su cómplice, pero no quiere: el Libro es para él.",
      "No puede recogerlo: no está en el suelo.",
    ],
    ru: [
      "Волшебная книга стоит в витрине кабинета. Искать её нельзя: он и так знает, где она.",
      "Он открывает витрину золотым ключом.",
      "Он хочет открыть Книгу и творить по ней свои слова. Он может её открыть и может ею воспользоваться: венчик будит Книгу.",
      "Но этой ночью открывать её не нужно: номер рецепта уже есть в документах.",
      "Он может её унести и спрятать: кухня рядом.",
      "Этой ночью он обязан отнести Книгу на кухню и спрятать под крышкой подноса. Он хочет унести и спрятать: это его главный план.",
      "Может отдать её сообщнику, но не хочет: Книга нужна ему самому.",
      "Поднимать её нельзя: она не на полу.",
    ],
  },
  llave_dorada: {
    es: [
      "La llave dorada abre la vitrina del Libro. Está en el bolsillo de Don Verbo, como siempre.",
      "El intruso no puede buscarla: todo el palacio sabe dónde está. Y no puede recogerla: no está en el suelo.",
      "A medianoche, Don Verbo duerme en su sillón. El intruso saca la llave de su bolsillo.",
      "Quiere usarla, puede usarla y tiene que usarla: con ella abre la vitrina.",
      "Puede llevarla a casa o dársela a su cómplice, pero no quiere.",
      "Después puede guardarla otra vez en el bolsillo: Don Verbo no se despierta. Y tiene que guardarla allí. Así nadie ve nada.",
      "Por eso esta mañana la llave está en su sitio.",
    ],
    ru: [
      "Золотой ключ открывает витрину Книги. Он, как всегда, в кармане Дона Вербо.",
      "Искать его нельзя: весь дворец знает, где он. И поднимать нельзя: он не на полу.",
      "В полночь Дон Вербо спит в кресле. Преступник достаёт ключ из его кармана.",
      "Он хочет им воспользоваться, может и обязан: этим ключом он открывает витрину.",
      "Может унести ключ домой или отдать сообщнику, но не хочет.",
      "Потом он может положить ключ обратно в карман: Дон Вербо не просыпается. И обязан положить. Так никто ничего не заметит.",
      "Поэтому утром ключ на своём месте.",
    ],
  },
  reloj_palacio: {
    es: [
      "El reloj está en la pared del pasillo. De noche el pasillo está oscuro: el intruso puede buscarlo con la mano.",
      "Quiere usar el reloj para saber la hora. Puede usarlo: el reloj funciona bien. Y tiene que usarlo: a las tres cambia el guardia.",
      "El reloj tiene una pequeña puerta de cristal. El intruso no quiere abrirla: hace ruido.",
      "Pero tiene que abrirla: detrás del cristal, Don Verbo ha escondido la varilla dorada. Y puede abrirla: no tiene llave.",
      "No puede llevarlo, guardarlo ni dárselo a nadie: está en la pared.",
      "Por eso esta mañana la puerta de cristal está abierta.",
    ],
    ru: [
      "Часы висят на стене в коридоре. Ночью в коридоре темно: преступник может нащупать их рукой.",
      "Он хочет посмотреть на часы, чтобы узнать время. И может: часы идут точно. И обязан: в три часа меняется охрана.",
      "У часов маленькая стеклянная дверца. Открывать её он не хочет: она скрипит.",
      "Но обязан открыть: за стеклом Дон Вербо спрятал золотой венчик. И может: замка у дверцы нет.",
      "Унести часы, спрятать или отдать нельзя: они на стене.",
      "Поэтому утром стеклянная дверца открыта.",
    ],
  },
  lupa: {
    es: [
      "La lupa de Don Verbo está en la mesa del salón, a la vista de todos. El intruso no puede buscarla: está delante de él.",
      "Los números de los documentos son muy, muy pequeños. Sin lupa, el intruso no puede leerlos.",
      "Quiere recoger la lupa y usarla. Y puede recogerla y usarla: nadie la vigila.",
      "Tiene que llevarla al despacho y tiene que usarla: con la lupa lee el número de la receta.",
      "Puede llevarla a casa, guardarla en el bolsillo o dársela a su cómplice, pero no quiere. Solo la lleva al despacho y después otra vez a la mesa.",
      "No puede abrirla: es una lupa.",
    ],
    ru: [
      "Лупа Дона Вербо лежит на столе в гостиной, у всех на виду. Искать её нельзя: она прямо перед ним.",
      "Цифры на документах очень-очень мелкие. Без лупы преступник их не прочитает.",
      "Он хочет взять лупу и воспользоваться ею. И может взять и воспользоваться: её никто не сторожит.",
      "Он обязан отнести её в кабинет и воспользоваться: через лупу он читает номер рецепта.",
      "Может унести её домой, положить в карман или отдать сообщнику, но не хочет. Только относит в кабинет и потом обратно на стол.",
      "Открыть её нельзя: это лупа.",
    ],
  },
  sobre_lacrado: {
    es: [
      "El intruso ha escrito un mensaje para su cómplice: cuándo sale la bandeja del palacio.",
      "Lo guarda en un sobre y lo cierra con cera roja.",
      "Quiere dar el sobre a su cómplice. No quiere salir al jardín con el sobre: es peligroso.",
      "Pero tiene que llevarlo al jardín y dárselo: sin el mensaje, el cómplice no sabe nada.",
      "Puede abrirlo otra vez para cambiar algo. Puede guardarlo en el bolsillo, llevarlo y dárselo a su cómplice. Si se cae, puede recogerlo. Si lo pierde, puede buscarlo.",
      "Pero no puede usarlo: el mensaje no es para él.",
      "Esta mañana el sobre está en la mesa. El plan no ha terminado: el cómplice todavía espera.",
    ],
    ru: [
      "Преступник написал сообщнику записку: когда поднос выйдет из дворца.",
      "Он кладёт её в конверт и запечатывает красным сургучом.",
      "Он хочет передать конверт сообщнику. Выходить с ним в сад он не хочет: опасно.",
      "Но обязан отнести конверт в сад и отдать: без записки сообщник ничего не знает.",
      "Он может снова открыть конверт, чтобы что-то поменять. Может положить его в карман, отнести и отдать сообщнику. Если уронит — может поднять. Если потеряет — может искать.",
      "Но воспользоваться им не может: записка не для него.",
      "Утром конверт лежит на столе. План не закончен: сообщник всё ещё ждёт.",
    ],
  },
  sombra_sala: {
    es: [
      "La sombra del jardín no es una cosa: es el cómplice del intruso. Espera en la oscuridad, junto a la Sala.",
      "El intruso quiere buscarla: tiene un mensaje para su cómplice.",
      "Puede buscarla en el jardín: de noche nadie lo ve.",
      "Y tiene que buscarla: sin el cómplice, el plan no termina.",
      "No puede abrirla, llevarla, recogerla, guardarla, usarla ni dársela a nadie: es una sombra.",
      "El ayudante más joven la ha visto: una sombra que espera.",
    ],
    ru: [
      "Тень в саду — не вещь, а сообщник преступника. Он ждёт в темноте возле Зала.",
      "Преступник хочет её найти: у него записка для сообщника.",
      "Искать её он может в саду: ночью его никто не видит.",
      "И обязан найти: без сообщника план не закончится.",
      "Открыть, унести, поднять, спрятать, использовать или отдать её нельзя: это тень.",
      "Самый младший помощник её видел: тень, которая ждёт.",
    ],
  },
};
